INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'ross@ross.com',
        TRUE);

INSERT INTO recipe (title, description, instructions, tag)
VALUES
('Chicken Cordon Bleu', 'Ham and swiss filled chicken breast with dijon cream sauce', 'Pound out your chicken breast thin.  Place a slice of ham and swiss on top. Keeping the sides tucked in, roll into a tight log.  Place log in flour, then egg wash, then in panko.  Bake at 350 until internal temperature reaches 165 Fahrenheit degrees. For sauce: sautee shallots and garlic. Add white wine and reduce by half. Add heavy cream, dijon and season to taste. Recommended sides: smashed potatoes and a garden salad. Serves: 2', 'Poultry'),
('Airline Chicken Breast', 'Pan roasted bone-in chicken breast with herb and garlic pan sauce', ' Heat a pan over medium heat. Add a small amount of oil and place chicken skin side down.  After 3-5 minutes, chicken should self release from pan and flip.  At this time, add the herbs, crushed garlic and chicken stock. Place in 375 degree over until temperature reaches 165 degrees Fahrenheit internal. Remove chicken from pan to rest. Use this pan and everything in it for sauce! For the sauce: Place the pan back over medium high heat, whisk in cold butter, adding a little at a time until desired consistency. Season to taste. Recommended sides: herb crusted fingerling potatoes, roasted vegetables. Serves: 2', 'Poultry'),
('Red Wine Braised Short Ribs', 'Slow cooked short ribs in a red wine and vegetable reduction', 'In a large dutch oven on high heat, sear all sides of the short ribs. Be careful to not overcrown the pan. Once all sides are brown, remove and put to the side. Lower the heat to medium low and add your mirepoix (celery, onions, carrots). Once softened, about 7 minutes, add garlic. Once fragrant, about 1 min, stir in and incorporate tomato paste.  It is ok if this caramelizes slightly Add wine and reduce by half. Wrap herbs in twine and add to pot. Add short ribs back to the pot, add chicken stock until just below top of short ribs. Bring to boil on stove top. Once boiling, put on lid, transfer to 300 degree Fahrenheit over for 3 hours. Carefully remove short ribs and place to the side. Remove herbs.  Using an immersion blender, blend the vegetables and liquid. This is a fantastic sauce with a deep rich flavor. Plate your short rib and ladle sauce on top. Recommended Sides: Mashed Potaoes, Roasted Broccoli. Serves 4', 'Beef'),
('Sesame Crusted Tuna', 'Asian Inspired seared tuna steak', 'Make your wasabi mayo combining wasabi and mayo to your desired spicy level.  Add a layer sesame seeds (white, black, or both) to a plate.  Pat dry the tuna and press onto sesame seeds covering all sides. Get a pan on medium high heat. Once hot, add oil to coat the bottom.  Once oil is hot, lay your piece of tuna down.  After 20 seconds, flip.  After 20 seconds, remove from pan. Slice semi-thin on a bias against the grain of the tuna.  Drizzle with your wasabi mayo and hoisin sauce.  Recommended Side: White rice, seaweed salad. Serves: 2', 'Seafood'),
('Grilled Pork Chop', 'Bone-in Grilled pork chop with a cherry and bourbon pan sauce', 'Get your Pork chop on the grill, allowing a few minutes per side to get some grill marks on there.  Due to the size of these, we will be transferring them to a 350 degree Fahrenheit oven for about 20 minutes, or until internal temperature is 145 degrees Fahrenheit.  For sauce: While the pork cooks, set a pan on medium heat. Once hot, add bouron and allow to reduce by half. Add chicken stock. Once this is reduced by half, add cherries and a small amount of cherry juice. Once incorporated, whisk in cold butter in small amounts until desired consistency.  Season to taste. Liberally pour sauce over pork.  Recommonded sides: Duck Fat Fingerling potatoes, vegetable of your choice. Serves: 2', 'Pork'),
('Cast Iron New York Strip Steak', 'Perfectly seared and basted with butter, garlic, and herbs', 'Allow steaks to come to room temp before cooking as this allows for a more even cook. Set your cast iron on medium-high heat and allow to get thoroughly hot This will take about 7 minutes.  Once hot, add a small amount of oil.  Season your steaks liberally with your choice of seasoning - recommendations include: salt, pepper, onion power, garlic powder. Place steaks in pan and press down firmly on them. Do not move the steaks. This will help a better crust form. After 3 minutes, flip steaks. Add herbs, garlic and butter. Tilt the pan towards you and with a large spoon baste the steaks. Do this for another 3 minutes or internal temperature reaches your desired doneness.  Rest steaks for 5 minutes before slicing.  Serve with your choice sides. Serves: 2.', 'Beef'),
('Flounder en Papillote', 'Flounder steamed with vegetables, white wine and herbs', 'Start by slicing your shallot, summer squash and zucchini thin.  Cut cherry tomatoes in half. Mix your vegetables and tomatoes. For each piece of fish: lay the mixture at the center of a large piece of parchment paper.  Lay the flouder on top, ensuring its relatively flat. Drizzle white wine on top. Sprink of salt and pepper. Slice lemon. Lay herbs, then lemon slices on top.  Bring 2 opposite edges of parchment together, and fold/roll down until tight.  Take 2 remaining edges, fold over and tuck underneath fish.  This "pouch" of fish should be relatively tight and sealed.  Bake at 375 for approximitely 13 minutes. Recommended Side: Rice. Serves 2.', 'Seafood');

INSERT INTO ingredient (name)
VALUES 
('Chicken Breast'),
('Sliced Ham'),
('Sliced Swiss Cheese'),
('Flour'),
('Eggs'),
('Panko'),
('Shallot'),
('Garlic'),
('White Wine'),
('Heavy Cream'),
('Dijon Mustard'),
('Airline Chicken Breast'),
('Thyme'),
('Rosemary'),
('Chicken Stock'),
('Butter'),
('Short Ribs'),
('Celery'),
('Onion'),
('Carrots'),
('Tomato Paste'),
('Red Wine'),
('Wasabi'),
('Mayonnaise'),
('Sesame Seeds'),
('8oz Tuna Steak'),
('Hoisin Sauce'),
('14oz Bone-In Pork Chop'),
('Luxardo Cherries'),
('Bourbon'),
('12oz Boneless New York Strip Steak'),
('6oz Flounder Filet'),
('Zucchini'),
('Summer Squash'),
('Cherry Tomatoes'),
('Lemon');

INSERT INTO recipe_ingredient (recipe_id, ingredient_id, quantity, unit)
VALUES 
(1, 1, 1, 'pound'),
(1, 2, .25, 'pound'),
(1, 3, .25, 'pound'),
(1, 4, 1, 'cup'),
(1, 5, 4, 'whole'),
(1, 6, 1, 'cup'),
(1, 7, 1, 'whole'),
(1, 8, 1, 'clove'),
(1, 9, .5, 'cup'),
(1, 10, .5, 'cup'),
(1, 11, 1, 'tablespoon'),
(2, 12, 2, 'whole'),
(2, 13, 3, 'sprigs'),
(2, 14, 2, 'sprigs'),
(2, 15, 1, 'cup'),
(2, 16, 4, 'tablespoons'),
(2, 8, 3, 'cloves'),
(3, 17, 3, 'pounds'),
(3, 18, 2, 'stalks'),
(3, 19, 1.5, 'whole'),
(3, 20, 3, 'whole'),
(3, 21, 4, 'ounces'),
(3, 22, 2, 'cups'),
(3, 8, 4, 'cloves'),
(3, 13, 6, 'sprigs'),
(3, 14, 3, 'sprigs'),
(3, 15, 4, 'cups'),
(4, 23, 1, 'tablespoon'),
(4, 24, .5, 'cup'),
(4, 25, 1, 'cup'),
(4, 26, 2, 'each'),
(4, 27, 2, 'tablespoons'),
(5, 28, 2, 'each'),
(5, 29, 8, 'each'),
(5, 15, 2, 'cups'),
(5, 16, 4, 'tablespoons'),
(5, 30, 4, 'ounces'),
(6, 31, 2, 'each'),
(6, 13, 3, 'sprigs'),
(6, 14, 1, 'sprig'),
(6, 8, 3, 'cloves'),
(6, 16, 4, 'tablespoons'),
(7, 32, 2, 'Each'),
(7, 33, 1, 'whole'),
(7, 34, 1, 'whole'),
(7, 35, 10, 'each'),
(7, 36, 1, 'each'),
(7, 9, .25, 'cup'),
(7, 13, 4, 'sprigs'),
(7, 14, 2, 'sprigs'),
(7, 7, 1, 'each');

INSERT INTO user_favorites(user_id, recipe_id)
VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5);